- name: 'Configure /etc/hosts for all LAB hosts'
  blockinfile:
    path: /etc/hosts
    marker: "# LAB HOSTS"
    block: |
      172.18.0.2  mk8s-master
      172.18.0.10 mk8s-worker1
      172.18.0.11 mk8s-worker2
      
- name: 'Delete unnecessary entries from /etc/hosts file'
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: '^127.0.1.1 mk8s'

